### ISSUE TITLE
Integration with ArcGIS JavaScript results in multipleDefine errors

### ISSUE THREAD

**Issue by lwilbourn** [js-cookie/js-cookie#56]
When placing the script for jquery-cookie within the same page as ArcGIS javascript. The following errors occur:

```javascript
Error: multipleDefine
    at Error (native)
    at c (http://js.arcgis.com/3.8/init.js:15:378)
    at Ka (http://js.arcgis.com/3.8/init.js:36:286)
    at http://js.arcgis.com/3.8/init.js:37:216
    at e (http://js.arcgis.com/3.8/init.js:15:291)
    at Ya (http://js.arcgis.com/3.8/init.js:37:194)
    at s (http://js.arcgis.com/3.8/init.js:34:301)
    at HTMLScriptElement.<anonymous> (http://js.arcgis.com/3.8/init.js:39:128)(anonymous function) @ init.js:40(anonymous function) @ init.js:19e @ init.js:15p.signal @ init.js:19Ka @ init.js:36(anonymous function) @ init.js:37e @ init.js:15Ya @ init.js:37s @ init.js:34(anonymous function) @ init.js:39
init.js:41 src: dojoLoader
init.js:41 info: Object {pid: "esri", mid: "esri/nls/jsapi_en-us", pack: Object, url: "http://js.arcgis.com/3.8/js/esri/nls/jsapi_en-us.js", executed: 0…}

> $.cookie("test", 1);

VM1798:2 Uncaught TypeError: $.cookie is not a function
    at <anonymous>:2:3
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

**Comment by FagnerMartinsBrack** [comment]
> Uncaught TypeError: $.cookie is not a function

As from version 2.0.0, jQuery is not necessary anymore. Now instead of using `$.cookie` you should use `Cookies.get` or `Cookies.set`.

See https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0
