### ISSUE TITLE
'39. JSON handling' error whilst using the tester 

### ISSUE THREAD

**Issue by omagill** [js-cookie/js-cookie#95]
This is the current error I get;
```
JSON handling: Call to read all cookies with mixed json (2, 0, 2)
returns JSON parsed cookies
Expected: 	
{
  "c": {
    "foo": "bar"
  },
  "c2": "v"
}
Result: 	
{
  "c": {
    "foo": "bar"
  },
  "c2": "v",
  "date": "Wed May 13 2015 00:00:00 GMT+0300 (Turkey Summer Time)"
}
Diff: 	
{
  "c": {
    "foo": "bar"
  },
  "c2": "v",
  "date": "Wed May 13 2015 00:00:00 GMT+0300 (Turkey Summer Time)"
}
Source: 	
    at Object.<anonymous> (http://localhost/testfacility/tester/test/tests.js:342:9)
returns unparsed cookies
Expected: 	
{
  "c": "{\"foo\":\"bar\"}",
  "c2": "v"
}
Result: 	
{
  "c": "{\"foo\":\"bar\"}",
  "c2": "v",
  "date": "Wed May 13 2015 00:00:00 GMT+0300 (Turkey Summer Time)"
}
Diff: 	
{
  "c": "{\"foo\":\"bar\"}",
  "c2": "v",
  "date": "Wed May 13 2015 00:00:00 GMT+0300 (Turkey Summer Time)"
}
Source: 	
    at Object.<anonymous> (http://localhost/testfacility/tester/test/tests.js:343:9)
Source: at http://localhost/testfacility/tester/test/tests.js:339:7
```

**Comment by FagnerMartinsBrack** [comment]
I'm sorry but I don't understand. Are you trying to run the project's test suite?

**Comment by omagill** [comment]
yes, I wanted to check whether everything was working because it doesn't set to cookie for some reason while everything is there placed correctly. Oddly though this is the only issue I've had when I ran the tester for the first time, later on though some other test scripts gave errors.

**Comment by FagnerMartinsBrack** [comment]
What is testfacility? Did you run `npm install` and then `grunt`?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
